### PR TITLE
[aform, atable] added file attach component

### LINKED ISSUE #64: [AForm][ATable] File Attach Component
https://vueuse.org/core/useFileDialog/

Should work in both AForm and ATable

### PR DESCRIPTION
**Pull request by Alchez**
Continuing from #122

### CODE REVIEW

**Comment by Alchez** [comment]
@bhattdevarsh @crabinak I've rebased the previous changes against the latest `development` branch, which has seen a significant rework. When you guys pull this branch, please run the following commands:

```
rush purge
rush update
rush rebuild
```

**Comment by crabinak** [comment]
@Alchez Thanks. I noticed trying to run this now (rushx story:dev) doesn't use Histoire anymore. Has this been updated?

**Comment by Alchez** [comment]
@crabinak Sorry, I should've mentioned that in the previous comment. All the stories have been consolidated into the `examples` folder. You should run the following to start the Histoire server now:

```
cd examples
rushx dev:atable (spawns the ATable stories)
rushx dev:aform (spawns the AForm stories)
```

**Comment by crabinak** [comment]
@Alchez Thanks! I'm receiving this error when I try to run `rushx dev:aform` or `rushx dev:atable`

_throw new Error(`No support plugin found for file ${absoluteFilePath}`);_
 
 Am I missing something? I ran `rush purge && rush update && rush rebuild` but still am unable to get Histoire running.

**Comment by agritheory** [comment]
@crabinak are you running this from the examples folder? We had to move all the specimens there to prevent a circular dependency problem with ATable and AForm.

**Comment by crabinak** [comment]
@agritheory I'm running this from the examples folder. I'm not sure what is causing this error. This is the case in the development branch as well. I don't know if anyone else ran into this error and had a quick fix for it. This is the full error if it gives any clues.

> file:///E:/Freelance/Agritheory/stonecrop/common/temp/node_modules/.pnpm/histoire@0.17.17_vite@5.3.2/node_modules/histoire/dist/node/stories.js:75
>         throw new Error(`No support plugin found for file ${absoluteFilePath}`);
>               ^
> 
> Error: No support plugin found for file E:/Freelance/Agritheory/stonecrop/examples/aform/date.story.vue
>     at addStory (file:///E:/Freelance/Agritheory/stonecrop/common/temp/node_modules/.pnpm/histoire@0.17.17_vite@5.3.2/node_modules/histoire/dist/node/stories.js:75:15)
>     at FSWatcher.<anonymous> (file:///E:/Freelance/Agritheory/stonecrop/common/temp/node_modules/.pnpm/histoire@0.17.17_vite@5.3.2/node_modules/histoire/dist/node/stories.js:41:27)
>     at FSWatcher.emit (node:events:519:28)
>     at FSWatcher.emitWithAll (E:\Freelance\Agritheory\stonecrop\common\temp\node_modules\.pnpm\chokidar@3.6.0\node_modules\chokidar\index.js:540:8)
>     at FSWatcher._emit (E:\Freelance\Agritheory\stonecrop\common\temp\node_modules\.pnpm\chokidar@3.6.0\node_modules\chokidar\index.js:632:8)
>     at NodeFsHandler._handleFile (E:\Freelance\Agritheory\stonecrop\common\temp\node_modules\.pnpm\chokidar@3.6.0\node_modules\chokidar\lib\nodefs-handler.js:400:14)
>     at NodeFsHandler._addToNodeFs (E:\Freelance\Agritheory\stonecrop\common\temp\node_modules\.pnpm\chokidar@3.6.0\node_modules\chokidar\lib\nodefs-handler.js:637:21)
> 
> Node.js v20.15.1
> Error: Failed calling cd atable/ && histoire dev.  Exit code: 1
>

**Comment by Alchez** [comment]
@crabinak

Usually that error shows up when the app can't find a valid Vite file with the Histoire-Vue plugin, which makes me think it might be a dependency issue (atleast because it works for me across multiple devices after purging old builds).

Can I ask you to remove any `node_modules` folders that may exist and trying again?

**Comment by crabinak** [comment]
@Alchez Thanks for the suggestions. Unfortunately, I had no luck with that. I found that running `pnpm run dev:aform` works for me. This might have to be my workaround for now.

**Comment by crabinak** [comment]
@agritheory Here are some screenshots of the styled file attach component.

file-attach-01
file-attach-02

I also switched the form layout to use CSS grid instead of flexbox for a bit more control over form field sizes and positions.

**Comment by crabinak** [comment]
@agritheory I reverted the form fields back to flex box as per our discussion. 
aform-flex-file-attach

**Pull request merged**
